/*  File generated by: Map Ed v0.98.5 */

#include "gba_input.h"

extern const u16 bgPalette[256];
#define bgPaletteLen 512
extern const u16 bgTiles[6816];
#define bgTilesLen 13632
extern const u16 bgMap1[4800];
#define bgMap1Len 9600
extern const u16 bgMap[4800];
#define bgMapLen 9600
extern const u16 bgCollision[4800];
#define bgCollisionLen 9600
